### ISSUE TITLE
增量公式是不是有问题

### ISSUE THREAD

**Issue by MarkAcee** [Niyunfeng/PID#1]
//增量误差
sptr->iIncpid= sptr->Proportion * sptr->iError
				- sptr->Integral * sptr->LastError
				+ sptr->Derivative * sptr->PrevError;

pid.c的31行是不是有问题？
我理解的是以下的写法，不对的地方，还望赐教
sptr->iIncpid= sptr->Proportion * (sptr->iError - sptr->LastError)
					+ sptr->Integral * sptr->iError
					+ sptr->Derivative * (sptr->iError - 2 * sptr->LastError + sptr->PrevError);

![image](https://user-images.githubusercontent.com/20577449/60763069-433fa700-a09f-11e9-82dd-3c1677badb66.png)

**Comment by Niyunfeng** [comment]
已修改，谢谢
